version: '3.7'
services:
  app-server:
    image: franciscocfreire/java-usuarios-microservice:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    restart: always
    networks:
      - backend

networks:
  backend:
