version: '3.7'
services:
  app-usuario:
    image: franciscocfreire/java-usuarios-microservice:1.1
    ports:
      - "5000:8080"
    restart: always
    networks:
      - backend
  app-drone:
    image: franciscocfreire/java-drone-microservices:1.3
    ports:
      - "5001:8080"
    restart: always
    networks:
      - backend
  app-angular:
    image: franciscocfreire/ang-skyview:1.0
    ports:
      - 3000:80
    networks:
      - frontend
networks:
  backend:
  frontend:
